# Generated by Django 5.2.1 on 2025-05-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
