# Generated by Django 5.2.1 on 2025-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_id',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
