# Generated by Django 5.2.1 on 2025-05-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicsapp', '0003_alter_product_category_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
