# Generated by Django 5.2.1 on 2025-05-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_created_at_product_orders_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orders_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
