# Generated by Django 5.1.7 on 2025-05-09 13:09

import django.core.validators
import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default=sales.models.generate_product_id, editable=False, max_length=6, unique=True)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, "+" and "-" are allowed.', regex='^[A-Za-z0-9\\s\\+\\-]+$')])),
                ('category', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Category must contain only letters and spaces.', regex='^[A-Za-z\\s]+$')])),
                ('price', models.DecimalField(decimal_places=2, help_text='Must be a positive number greater than 0.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity', models.PositiveIntegerField(help_text='Must be a whole number greater than 0.', validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Color must contain only letters and spaces.', regex='^[A-Za-z\\s]+$')])),
            ],
        ),
    ]
