# Generated by Django 5.1.7 on 2025-05-09 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, "+" and "-" are allowed.', regex='^[\\w\\s+-]+$')]),
        ),
    ]
