# Generated by Django 5.2.1 on 2025-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('category', models.CharField(choices=[('Smart Phones', 'Smart Phones'), ('Fashion', 'Fashion'), ('Interior Design', 'Interior Design'), ('Laptops', 'Laptops')], max_length=100, verbose_name='Category')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('image', models.ImageField(upload_to='', verbose_name='Upload Image')),
            ],
        ),
    ]
