# Generated by Django 5.2.1 on 2025-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_page', '0002_alter_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(verbose_name='Upload Image'),
        ),
    ]
