# Generated by Django 5.2.1 on 2025-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
                ('category', models.CharField(choices=[('Smart Phones', 'Smart Phones'), ('Fashion', 'Fashion'), ('Interior Design', 'Interior Design'), ('Laptops', 'Laptops')], null=True)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
