# Generated by Django 5.2.1 on 2025-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('Quantity', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
