# Generated by Django 5.2.1 on 2025-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_at',
            field=models.DateField(auto_now=True),
        ),
    ]
